#!/usr/bin/env python3
"""Inline styles.css into the <head> of every page.

Why: on simulated slow-4G the separate /styles.css request added ~480 ms of
render-blocking time after the HTML (it was the second longest node of the
critical path). Inlining means the page can paint as soon as the head arrives -
one less request, one less round trip, same bytes once compressed.

Run AFTER every Tailwind rebuild:
    python tools/inline_css.py
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES = ['index.html', 'privacy.html', 'terms.html']
BEGIN = '<!-- CSS:BEGIN generated by tools/inline_css.py, do not edit -->'
END = '<!-- CSS:END -->'


def main():
    css_path = os.path.join(ROOT, 'styles.css')
    if not os.path.exists(css_path):
        sys.exit('styles.css not found - run Tailwind first')
    with io.open(css_path, encoding='utf-8') as fh:
        css = fh.read()
    if '</style' in css.lower():
        sys.exit('styles.css contains </style - refusing to inline')

    style = '<style>%s</style>' % css.strip()
    for name in PAGES:
        path = os.path.join(ROOT, name)
        with io.open(path, encoding='utf-8') as fh:
            html = fh.read()
        i, j = html.find(BEGIN), html.find(END)
        if i < 0 or j < 0:
            sys.exit('%s: CSS markers not found' % name)
        start, end = i + len(BEGIN), j
        html = html[:start] + '\n' + style + '\n' + html[end:]
        with io.open(path, 'w', encoding='utf-8', newline='') as fh:
            fh.write(html)
        print('%-14s inlined %.1f KiB' % (name, len(css) / 1024.0))


if __name__ == '__main__':
    main()
